### ISSUE TITLE
All or nothing not showing in Canvas

### ISSUE THREAD

**Issue by rfaust1963** [jamesjonesmath/canvancement#16]
Good morning, 
We use the Quiz Whiz: All or nothing to grade our select all that applies.  It is not working, nor even showing up on our computers. Please help!

**Comment by jamesjonesmath** [comment]
I just double checked and the button is still showing up for me in Chrome with a PC. It also works when I click on it. That suggests that it's not a problem with QuizWiz, or at least not still a problem with QuizWiz. 

Thankfully, QuizWiz has been fairly stable since writing it except for intermittent problems with the content delivery network messing it up. Those fix themselves. I did clear my cache in the browser, but you asked the questions 8 hours ago and it may have resolved itself by now.

If that's not the issue, then your report gives me little to go on to track down the issue. About all I can do is ask questions to get at what is happening or make generalized comments about problems other people have had. This has all been done before in the Canvas Community post on QuizWiz.

* You don't say if it used to be working and just stopped or if it has never worked. 
* You don't mention if you're using it through Tampermonkey or have installed it in a global custom JavaScript file for the entire institution. 
* You don't mention what operating system you're using and it seems that recent versions of Safari aren't going to support Tampermonkey, which means that it may be impossible to install it in Safari moving forward.

If Tampermonkey is set up but the script isn't running (there's not a red numbered badge on the icon when you visit SpeedGrader in Canvas), then it's possible (probable) that you are running a custom domain for your Canvas rather than at instructure.com. If your Canvas site is `canvas.institution.edu` instead of `institution.instructure.com`, then you need to set the custom domain as explained in the documentation.

The best I can do without additional information has been already answered online in the Canvas Community. You may want to read through the [thread in the Canvas Community](https://community.canvaslms.com/docs/DOC-8251-quizwiz-enhancements-to-speedgrader-and-quizzes) and see if there is something there that will help.

I also prefer to help people through the Canvas Community rather than through GitHub. That forum has greater exposure and explanations and it's easier to provide formatted responses and screen shots.

**Comment by dogboy87** [comment]
I have been using Quiz Whiz for over a year and it was working fine until today. I am on a MAC, using CHROME. Everything is up to date. It worked as recently as yesterday.  I am using it through TAMPERMONKEY. 

Thanks

**Comment by jamesjonesmath** [comment]
Thanks. The $ is now undefined after the October 23 deployment. I have an idea of how to fix it, but am in meetings for a couple of hours and won’t be able to get to it until after that.

**Comment by jamesjonesmath** [comment]
I've updated the QuizWiz installation files to load the engine via pure JavaScript by adding the script to the head, rather than relying on jQuery's getScript() function.

Canvas made some optimizations so that all of the scripts that they use now deferred and not available when the document is ready. Tampemonkey injects the code before the Canvas scripts get loaded and the jQuery $ variable is undefined.

By loading the script through JavaScript, it still gets added to the document head before Canvas scripts do, but that's okay because it has Mutation Observers to wait until the content is actually ready.

**Comment by dogboy87** [comment]
Works great now. Thanks a bunch!
