### ISSUE TITLE
JSON data not parsing correctly

### ISSUE THREAD

**Issue by ricardo37** [jamesjonesmath/canvancement#19]
This script has been running fine for me for weeks. But today it terminated after only partial execution. See the attached screenshot of the resulting error message. I'm running Firefox for Mac 70.0.1 (64-bit version).

<img width="1551" alt="Screen Shot 2019-11-04 at 10 18 25 AM" src="https://user-images.githubusercontent.com/2636826/68137734-15ebf400-feed-11e9-9240-56c67ee9955e.png">

**Comment by jamesjonesmath** [comment]
Which script are you talking about? You have a peer_reviews mentioned in the screen shot, but I don't have a script called that. My scripts definitely don't call anything on nr-data.net, it's a tracking site.

**Comment by ricardo37** [comment]
I'm using IntraGroup Peer Reviews, a script for the Canvas LMS. Per the attached screenshot, the script maps to your namespace.

![Screen Shot 2019-11-04 at 6 57 01 PM](https://user-images.githubusercontent.com/2636826/68170360-0e503d80-ff35-11e9-84dd-20b338c8af94.png)

**Comment by jamesjonesmath** [comment]
Are you sure that the error message is related to the script? The 36 times the error message happened makes it sound like it's some kind of loop with an issue, so it could be, but it seems weird. Your institution didn't recently install a proxy server did it? You can check some of Canvas native network traffic and look for that.

I just loaded it and ran it fine on Chrome (Windows) and Firefox (Mac) so I'm having duplicating the code. It may be that you have too large of a class and/or there was network congestion at the time. You wrote this 9 hours ago. Is this still repeatable?

I will say that I am unlikely to do any error checking, so if it times out, it will probably fail, but the error message you gave just refers to the problem in the JSON data, which isn't returned, and not the line in the code where it happened. In cases this this, I think you should just be able to run the script again unless there is some bigger issue.

Since you're familiar with the developer tools, you can help by switching over to the network tab and look at the request that failed. What was the request header and what was the response? In particular, the response should be invalid JSON, but it may also be that there was an error in receiving the message.  If, for example, it starts off while(1); then I'm pretty sure it's missing an application/json accept header.

**Comment by ricardo37** [comment]
You're right that I'm not sure the error message is related to your script (though it doesn't appear until I actually run that script). Yes, my institution may have recently installed a new proxy server, or tweaked settings on an existing one. Next time I will try the script from home to see if I get better results. Or maybe, as you say, it was just a congestion issue earlier today and everything will be fine if I run it now.

I'm reluctant to try the script again right now, since I fear that my students get notifications every time a peer review is assigned, or reassigned, to them. I already ran the script about 5 times earlier today (since each successive run seemed to add a few more assignments before the script locked up again), so they're probably annoyed already.

But I will need to run the script again later this week for the next assignment in this class. If I run into any problems at that point, I will check the network tab and let you know what it says. I may try stepping through the program myself to see which instruction could be generating the problem. If the script works fine at that time, or if I can get it to work fine at least from home, I will add a comment here to let you know that.

Thanks for your help.

**Comment by ricardo37** [comment]
I ran the script again today and am pleased to report that it worked perfectly. So my best guess is that you were correct in supposing network congestion to be the problem. I will mark this item closed.
