### ISSUE TITLE
Partial Credit Script Gives Extra Points 

### ISSUE THREAD

**Issue by kacicohn** [jamesjonesmath/canvancement#21]
The partial credit script gives extra points if the student didn't check the correct number of answers.  For example, on a 1 point question, if the student was supposed to choose two answers, and they only chose one - the correct one - Canvas scores them with a 0.5 (the only time Canvas will provide partial credit because they didn't choose any incorrect answers.)

The script adds an extra 0.25 points to the student's score.

Is this something that is able to be fixed?

Thanks!

**Comment by jamesjonesmath** [comment]
This sounds like the expected behavior.

You didn't say how many choices were available.  If you have 4 responses, 2 are correct and 2 are incorrect, and you correctly mark just 1 of the correct ones, then they have correctly marked 3 out of the 4 parts. 1 / 2 correct were marked and 2 / 2 incorrect were not marked.

The Partial Credit option in QuizWiz does not mimic Canvas behavior, which is, in my opinion the best way. It was written for those people who think you should get credit for not marking a wrong answer or want the multiple answers to function as a set of true/false questions.

Please read the descriptions in the Canvas Community and see if that helps with the explanation.
* [QuizWiz: Enhancements to SpeedGrader and Quizzes](https://community.canvaslms.com/docs/DOC-8251-quizwiz-enhancements-to-speedgrader-and-quizzes) especially the section on Multiple-Answers Partial Credit based on the percentage of correctly answered responses
* [Understanding Multiple Answers Questions](https://community.canvaslms.com/docs/DOC-6674-understanding-multiple-answers-questions)
