### ISSUE TITLE
suggestion: enlarge "advance to next user" button?

### ISSUE THREAD

**Issue by jxshen311** [jamesjonesmath/canvancement#24]
It would be very nice if the button next to the "Update Scores" & "submit" link in quizzes to advance to the next user could be larger. It will save time to get the mouse cursor within the button area. It would be even nicer if a keybinding could be added for "Update Scores and advance to the next user". Thanks!

**Comment by jamesjonesmath** [comment]
Thank you for your suggestions.

As much as I value accessibility and keyboard usage and even sometimes wish I didn't have to move my mouse at all, I will not be doing either of these.

I tried to make the button as small as I could when I created it because of limited space. I didn't want a button as big as the primary button because I didn't want to replace the main Canvas functionality. I was trying to tweak it. I originally didn't have any overrides on the button and it was too big. So I tried using the mini-buttons and it was too smalI and it looked weird being a different height than the button right next to it. I finally ended up setting the padding to 1px on the left and the right.

If you would like to use the standalone version you can customize the advance.style.paddingLeft and advance.style.paddingRight in lines 299 and 300 to change it from 1px to a larger value.


As for the key binding, I have not done that in a long (17 years) time. Back then, it was through accesskey. A quick review of [keyboard accessibility](https://webaim.org/techniques/keyboard/accesskey) reminded me why I haven't done it recently.

My personal frustration with keyboard bindings and that I never remember what they are and they're not always application specific (my nVidia GEForce keyboard bindings work in any program and I have to disable them to get back the keybinding I actually use). So you pick something arbitrary and then you break someone else's bindings.

Also remember that there are potentially three spots on the page that have a save and advance option. Do you keybind for each of those? Do you make it a configuration switch where people specify what keybinding they would want to use? It's inside a function, so you would need to pass an option in of when to use it and what it should be.

The [Mozilla Developer Network page on accesskey](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) cites the WebAIM page when listing issues and ends with a recommendation: "Because of these issues, it is generally advised not to use accesskeys for most general-purpose websites and web apps."

My journey from that page took me to the [aria-keyshortcuts](https://www.w3.org/TR/wai-aria-1.1/#aria-keyshortcuts) portion of the Accessible Rich Internet Applications (WAI-ARIA) 1.1. Reading that and the related links I find there is still danger of aria-keyshortcuts and making sure to avoid conflicts. That might be doable if I added a configuration option for people to specify which keyboard shortcuts they wanted to use, but I still wouldn't want to specify one for people.

Adding them at all would require a configuration change since I wouldn't want to force them on people. That still doesn't fix the issue of which key binding to pick that people would know about and wouldn't interfere with something already in use. Most people don't even know that there are keyboard bindings for the Rich Content Editor because they are not visible, so this would likely go unused by many people.

That doesn't mean it's a perfect or recommend solution, though. The [MDN page on ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) says that developers should prefer using the correct semantic HTML element over using ARIA and specifically mentions keyboard accessibility. It says that built-in elements like button have built-in accessibility and you should use that instead of ARIA.

If you start trapping onkeydown, then you have to remember to pass through anything that isn't your key to Canvas.

In short, keyboard shortcuts are not something that I'm going to put into the program at this time. 

You can install the standalone version and modify it to add your own keybindings if you like in a way that doesn't cause conflicts for you. In that same function around line 292, you could add a check for options.shortcut like I have for size and title. If it defined and exists, then you add your code to do the keybinding. You would then need to search for the locations that called the advanceButton function and modify their options.

Alternatively, you could create your own fork and maintain a local copy. The nice thing about Tampermonkey is that it shows you a diff whenever there is an update, so if you modify it within the browser, then you can still keep in sync with my master. If you fork, you'll have to maintain your own copy (I don't know Git well enough to know what that involves and if it is easier).

**Comment by jxshen311** [comment]
Thank you for the detailed explanations and for the advice on workarounds!
