### ISSUE TITLE
Try to import a rubric. Clicked Create button and nothing happen

### ISSUE THREAD

**Issue by ronnyyau** [jamesjonesmath/canvancement#37]
![image](https://user-images.githubusercontent.com/61881555/105626756-cfecba00-5e29-11eb-87d0-26c9f3a5a419.png)
I am trying use make a test rubric into the canvas, but when i click create, nothing happen and no error message out, am i doing something wrong?
![image](https://user-images.githubusercontent.com/61881555/105626800-3540ab00-5e2a-11eb-8a2d-768524fa5cbd.png)

**Comment by jamesjonesmath** [comment]
What jumps out at me is that you have the same point values in each row. Point values within a criterion should be different because that is how Canvas sorts the entries. For example, you cannot use 0 multiple times within a row, but you could use 0 once in each row (multiple times in a column).

If you do not want to use points, you still have to put them into the rubric. Then, after creating the rubric, you can edit it and tell it not to use points.

**Comment by ronnyyau** [comment]
@jamesjonesmath Thank you so much for your reply, and it works now. Just one more question for me.

I am a University student which making a honours stage project. My project is making a feedback tool which helping academic to speed up their workload. I would like to kindly ask you if i can use your plugin for my project, and mention you and your plugin in my report?

**Comment by jamesjonesmath** [comment]
The code is licensed under the [ISC license](https://github.com/jamesjonesmath/canvancement/blob/master/LICENSE). It allows for what you want to do without having to get permission from me.
