### ISSUE TITLE
Thanks and feedback

### ISSUE THREAD

**Issue by bjones1** [jamesjonesmath/canvancement#44]
James, wow! I just discovered your site through the sort-rubric extension and I'm thrilled! Thanks for bringing these features to the Canvas community.

A quick note of feedback from me: at my institution, the Canvas URL is `https://canvas.msstate.edu` instead of the expected pattern of `https://*.instructure.com/courses/*/rubrics/*`. Changing this to `/^https:\/\/(canvas\..*\.edu|.*\.instructure\.com)\/courses\/[0-9]+\/rubrics\/[0-9]+/` [here](https://github.com/jamesjonesmath/canvancement/blob/master/rubrics/sort-rubric/sort-rubric.user.js#L5) made the script work (via Tampermonkey) for me. (FYI, I use https://regex101.com/ to create a regex...that helps me check  and refine my regex very easily.)

**Comment by jamesjonesmath** [comment]
You're welcome, I'm glad you found it helpful.

You are correct that if you use a custom domain, then you will need to change the include line to match your host. That is covered in the customization section of the documentation.

`canvas.*.edu` works for you and you're welcome to add it on your script, which is what I tell people with custom domains to do, but I'm not going to add canvas.*.edu as a regular expression to the scripts.

Here is my thinking on this.

1. It would confuse people who need to change them and who don't use `canvas.*.edu` as a host name. Regular expressions are difficult for people to get right. I have people who get confuse and try `*.canvas.institution.edu` instead of just `canvas.institution.edu` and that doesn't work, despite being a lot simpler than a regular expression.
2. I don't see much gain. Some institutions may use `canvas.*.edu`, but I've probably seen more that have a custom name name like elearning, online, or webcourses. There's no way I'm going to support everything because then it would end up running on a lot of sites where it shouldn't and I don't want to be "that guy" that shares software that crashes stuff. Beyond that, I've encountered issues with some schools that have custom domains also running proxies that break some of the scripts. I can test it on `*.instructure.com`, but I cannot verify that it will work on those other systems, so I don't support them directly. Part of my reputation is that it works (at least most of the time).
3. It's very US-centric. It won't work for other nations that have a country code at the end. This is related to number 2 with not seeing a lot of benefit to supporting one specific hostname, although that probably is the most common one outside of people who host with instructure.com. But for that limited benefit for the three people who use it at `canvas.*.edu`, it adds a lot of complexity.
4. There is no reason to use a regular expression at all. You can have multiple include lines in the metadata. Just put in two include lines, one for `*.instructure.com` and one for `canvas.*.edu`. However, if you want to use it at `canvas.msstate.edu`, you can just replace the `*.instructure.com` with that and it will keep that change in any updates (except perhaps major ones).

**Comment by bjones1** [comment]
Makes sense -- thanks for the quick response, and again for the great software you've written!
