### ISSUE TITLE
Page reloading required with quizwiz (standalone)

### ISSUE THREAD

**Issue by varlokkur** [jamesjonesmath/canvancement#45]
For the past week or so, I've had an issue with QuizWiz when grading quizzes in speedgrader: upon loading, it works fine for the first student, but after I click 'Update Scores' and advance to the next student's quiz, the button no longer works.  Whether I advance using the blue arrow to 'Update and advance to the next user' or use the built-in speedgrader advance button, the Update scores button ceases to have any effect.  I have to shift-reload the page to get it working again. 
I may try installing the tampermonkey addon in Chrome or Edge and getting that set up to try and see if this is a Firefox-specific issue or what, but I thought I would check in to see if this is a known issue caused by some update to Tampermonkey or canvas, etc.

**Comment by varlokkur** [comment]
Well, for better or worse I'm finding the same behavior in Edge.

**Comment by jamesjonesmath** [comment]
This was reported in the Canvas Community and I put out a fix for it on on March 9. It was a nasty thing that Canvas did and it took me a week to figure out the workaround. It doesn't have anything to do with Tampermonkey. It has to do with Canvas using Sentry to report crashes back to them and sentry not playing well with event listeners in iframes.

I tested the patch on Chrome, Firefox, Safari, and someone else tested it on Edge before I released it.

Can you double check that you have the latest version installed? If you have installed the standalone version, it should say version 5.2 in the metadata at the top. There were relatively few changes to the actual code, but it looks like a lot because I changed code formatters and it changed a lot. Tampermonkey may not have done the automatic upgrade because of that.

If you using a version that fetches from the internet each time you run it, then check the code to make sure that you are fetching the script from canvancement.s3.us-east-2.amazonaws.com and not gitcdn.link (which proved unreliable).

Canvas did address another issue they were having with the release today (March 19), but I tested my changes in beta before I released them to the public and it shouldn't affect the work-around I had to do. In other words, I check for the issue in Canvas and fall back to the old behavior if it's not there.

I just tested it myself with Chrome and it works and given that what you're describing is exactly the conversation we had in the Canvas Community that I fixed, my guess is that you're running a standalone version that needs updated. That doesn't explain why it doesn't work if you did a fresh install on Edge unless perhaps you copied the code from Chrome to Edge instead of installing fresh from GitHub.

**Comment by varlokkur** [comment]
That fixed it! Thank you.  I'm not sure why Tampermonkey didn't update the script; it looks like the settings are correct for checking for updates.  I'll try to figure that out another day, when the grading is all caught up. 

Thanks once again for creating and maintaining this!
