### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by mbomb007** [jamesjonesmath/canvancement#48]
Can you tag an official release, so that it's easier to see versioning and use this project as a dependency?

**Comment by jamesjonesmath** [comment]
This isn't a project in the normal sense, it's a collection of a bunch of loosely-related (I wrote them) pieces. The code is in multiple languages and is not suitable as a dependency for anything. There's not anything to tag as a release.

**Comment by jamesjonesmath** [comment]
Creating a composer.json file like that is a very bad idea. There are only 3 PHP files that I can find, none of which is being actively maintained and I'm pretty sure there are bugs in the one to create the MySQL scripts for Canvas Data. 

But the real reason is that this is not a PHP codebase. There is a very limited amount of PHP in there, but it's just a lot of hodge-podge stuff I do. Including it in composer is going to bring in a lot of extra crap that you don't need (98% crap for 2% useful code). You should not be making that a dependency for anyone else. It would be much better for you to make your own fork of just the one or two files that you think you want and then use that.

When I set this up, I didn't (still don't) know how to use GitHub. I don't have the time to refactor everything into separate programs and there are too many links to the code where it is.
