### ISSUE TITLE
list-admin-roles.user.js broken because of missing FileSaver.js

### ISSUE THREAD

**Issue by fuzzy76** [jamesjonesmath/canvancement#5]
https://github.com/eligrey/FileSaver.js has updated their file structure, so your userscript does not work any more. Any chance of an update?

**Comment by jamesjonesmath** [comment]
Thanks for letting me know about this as it's a script I don't use myself and I wouldn't have noticed it wasn't working.

The problem turned out even bigger. saveAs() changed the way it's exporting and the current version doesn't work with Tampermonkey. I ended up grabbing a slightly older version from a CDN until the problems are resolved and someone notifies me of another problem.

The second problem was that Canvas moved the Analytics link that I was using to determine where to add the button from the Courses page to its own Analytics page. That means that since December 9, 2017, it hasn't been working at all for anyone. I moved it to the People page where it probably fits more naturally anyway with the user groups and profile pictures.
