### ISSUE TITLE
Any way to do assignments with multiple due dates?

### ISSUE THREAD

**Issue by TeacherGale** [jamesjonesmath/canvancement#52]
My canvas was set up for me where all of my classes (per subject) are in a single canvas course, and students are split into sections. One of my subjects is on both A days and B days at my school, so one section needs to have one due date while the other four sections need a different due date. I was hoping to use this as it would make it super simple so I don't have to edit the same 40 assignments to set every due date correctly (I would rather not have to manually edit the due dates of 120 assignments)

Is there any way to do assignments with multiple due dates in canvancement?
Right now in the spreadsheet it sets the earliest of the five availability dates as the "Available until" time and the latest of the five due dates as the "Due" time

**Comment by jamesjonesmath** [comment]
The adjust all due dates Canvancement does not even attempt to handle differentiated assignments. The Canvas built-in adjust all due dates will provided that you have already differentiated them. You should talk to your Canvas admin about how they set up courses if you need different due dates for different sections because combining them together is a major pain. It may be that they didn't know any better.
