### ISSUE TITLE
Safari Sonoma OS Issues

### ISSUE THREAD

**Issue by nlopez11** [jamesjonesmath/canvancement#54]
I recently updated my operating system to Mac OS Sonoma. Since then, I have to install and reinstall Tampermonkey to get the scripts to work. This is happening with all the Canvancements that I installed onto my browser. The scripts are not loading and the widget on Safari does not indicate that a script is running.

**Comment by jamesjonesmath** [comment]
This is an issue with Sonoma and Tampermonkey, not the Canvancements themselves. There has been an issue filed on the [Tampermonkey GitHub site](https://github.com/Tampermonkey/tampermonkey/issues/1856) about it two weeks ago, but no solution as of yet.

It's not anything that I'm going to be able to help with other than to suggest trying Chrome instead of Safari until the issue is resolved. There may be other userscript managers that work, but I do not have a recommendation for you.
